### ISSUE TITLE
Issues resolving image @{} while using both context path and spring cloud gateway as reverse proxy

### ISSUE THREAD

**Issue by antechrestos** [thymeleaf/thymeleaf-spring#267]
# Runtime context

* springboot version 2.5.5
* spring cloud 2020.0.4
* Thymeleaf 2.0.12

# Context

I have two application: the first one is a spring cloud gateway running (let's say locally to make it easier it) with a simple discovery

```yaml

server:
  port: 8080

spring:
  cloud:
     gateway:
       discovery:
         locator:
           url-expression: "uri"
           predicates:
             - name: Path
               args:
                 patterns:
                   - "'/' + serviceId + '/**'" 
           filters:
             - name: RewritePath
               args:
                 regexp: "'/' + serviceId + '/?(?<remaining>.*)'" 
                 replacement: "'/${remaining}'"
    discovery:
      client:
        simple:
          instances:
            gui:
               - uri: http://localhost:${aas.local.ports.admin}
                  metadata:
                    management.context-path: /manage
```

And the proxified spring boot named gui with following configuration

```yaml

server:
  port: 8081
  forward-headers-strategy: "FRAMEWORK"
```

With this configuration (without context path for gui application), any use of `@{/js/resource.js}` for example, will work like charm when gui application is accessed through spring gateway application. 

For instance, provided that `/home` endpoint of gui application serve a template that has `th:src=@{/js/my-js.js}`, when accessing

http://localhost:8080/gui/home, the computed url of js in served page will be http://localhost:8080/gui/js/my-js.js.

Also, while working directly on gui application, I can access to my endpoint through http://localhost:8081/home and it will resolve js address to http://localhost:8081/js/my-js.js

So far so good.

However, when I put a context path on my gui application, things are a little bit different.

I set then `server.servlet.context-path: /my/context/path` on **gui** application and while navigating to http://localhost:8081/gui/my/context/path/home, it serves me the computed template  with computed url pointing to http://localhost:8080/gui/js/my-js.js instead of http://localhost:8080/gui/my/context/path/js/my-js.js .

Accessing gui directly (http://localhost:8081/my/context/path/home) does resolve js with context path to http://localhost:8081/my/context/path/js/my-js.js

Anything that I am missing?

Thank you
