### ISSUE TITLE
Problem changing templates folder

### ISSUE THREAD

**Issue by callor** [thymeleaf/thymeleaf-spring#332]
I want to change the resources/templates folder to resources/views in a spring boot project.

However, if I change the templates folder to a different name (I use views), the Controller does not recognize the folder. When I run the project and execute the Request, the *.html file is loaded normally and displayed on the screen. However, it is inconvenient because a warning (or error) keeps appearing in the IntelliJ IDE. Please tell me how to solve it.

![Image](https://github.com/user-attachments/assets/9e0c7805-7899-48fe-a758-a13673887479)

The `resources/application.yaml` file is set as follows:

```yaml
spring:
  application:
    name: myapp

  thymeleaf:
    prefix: classpath:/views/
    suffix: .html
    mode: HTML
    cache: false
```

The views folder of the project is as follows:

![Image](https://github.com/user-attachments/assets/683b6084-1f68-420a-8373-deab3565003a)
